// ─── Shared data across all pages ────────────────────────────────────────────

export const SOCIALS = [
  { label: "LinkedIn",    href: "https://linkedin.com/in/ammaricano" },
  { label: "GitHub",      href: "https://github.com/ammaricanooo" },
  { label: "Instagram",   href: "https://instagram.com/ammaricano" },
  { label: "Threads", href: "https://threads.com/@ammaricano" },
];

export const WORK_PROJECTS = [
  {
    id: "01",
    title: "DISKOMINFO Company profile",
    tech: "Laravel, Tailwind, MySQL",
    url: "#",
    year: "2024",
    desc: "Company profile website for the Department of Communication and Information Technology, featuring dynamic content management and responsive design.",
    img: "diskominfo.png",
  },
  {
    id: "02",
    title: "Arsana Tarangga",
    tech: "Next.js, Tailwind",
    url: "https://arsana-tarangga.vercel.app/",
    year: "2025",
    desc: "Paskibra organization website with event scheduling, member management, and interactive photo galleries.",
    img: "arsana.png",
  },
  {
    id: "03",
    title: "Al-Qur'an Ku",
    tech: "Next.js, Tailwind, FireBase",
    url: "https://quran.ammaricano.my.id/",
    year: "2024",
    desc: "Digital Qur'an reader with surah navigation, verse bookmarking, and audio recitation support.",
    img: "alquranku.png",
  },
  {
    id: "04",
    title: "PPDB SMK Bina Informatika",
    tech: "Next.js, Tailwind",
    url: "https://bifor.ammaricano.my.id/",
    year: "2024",
    desc: "Online student registration system for SMK Bina Informatika, featuring form submission, document upload, and admin approval workflow.",
    img: "biforppdb.png",
  },
  {
    id: "05",
    title: "Parqeer",
    tech: "Laravel, Tailwind, MySQL",
    url: "#",
    year: "2023",
    desc: "Real-time parking slot management system with live availability updates via WebSocket.",
    img: "parqeer.png",
  },
  {
    id: "06",
    title: "Arnime",
    tech: "Next.js, Tailwind, FireBase",
    url: "#",
    year: "2023",
    desc: "Anime streaming platform with server-side rendering, dynamic routing, and PostgreSQL-backed watchlist.",
    img: "arnime.png",
  },
  {
    id: "07",
    title: "Nexure API",
    tech: "Node.js, Express.js",
    url: "#",
    year: "2023",
    desc: "RESTful API boilerplate with JWT auth, role-based access control, and auto-generated docs.",
    img: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=900&auto=format&fit=crop",
  },
  {
    id: "08",
    title: "Telebot Go",
    tech: "Golang",
    url: "#",
    year: "2023",
    desc: "Telegram bot built in Go with command routing, webhook support, and automated message scheduling.",
    img: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=900&auto=format&fit=crop",
  },
];
