
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TechCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TechCategory
 * 
 */
export type TechCategoryModel = runtime.Types.Result.DefaultSelection<Prisma.$TechCategoryPayload>

export type AggregateTechCategory = {
  _count: TechCategoryCountAggregateOutputType | null
  _avg: TechCategoryAvgAggregateOutputType | null
  _sum: TechCategorySumAggregateOutputType | null
  _min: TechCategoryMinAggregateOutputType | null
  _max: TechCategoryMaxAggregateOutputType | null
}

export type TechCategoryAvgAggregateOutputType = {
  order: number | null
}

export type TechCategorySumAggregateOutputType = {
  order: number | null
}

export type TechCategoryMinAggregateOutputType = {
  id: string | null
  order: number | null
  label: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechCategoryMaxAggregateOutputType = {
  id: string | null
  order: number | null
  label: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TechCategoryCountAggregateOutputType = {
  id: number
  order: number
  label: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TechCategoryAvgAggregateInputType = {
  order?: true
}

export type TechCategorySumAggregateInputType = {
  order?: true
}

export type TechCategoryMinAggregateInputType = {
  id?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
}

export type TechCategoryMaxAggregateInputType = {
  id?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
}

export type TechCategoryCountAggregateInputType = {
  id?: true
  order?: true
  label?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TechCategoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechCategory to aggregate.
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechCategories to fetch.
   */
  orderBy?: Prisma.TechCategoryOrderByWithRelationInput | Prisma.TechCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TechCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TechCategories
  **/
  _count?: true | TechCategoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TechCategoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TechCategorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TechCategoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TechCategoryMaxAggregateInputType
}

export type GetTechCategoryAggregateType<T extends TechCategoryAggregateArgs> = {
      [P in keyof T & keyof AggregateTechCategory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTechCategory[P]>
    : Prisma.GetScalarType<T[P], AggregateTechCategory[P]>
}




export type TechCategoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechCategoryWhereInput
  orderBy?: Prisma.TechCategoryOrderByWithAggregationInput | Prisma.TechCategoryOrderByWithAggregationInput[]
  by: Prisma.TechCategoryScalarFieldEnum[] | Prisma.TechCategoryScalarFieldEnum
  having?: Prisma.TechCategoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TechCategoryCountAggregateInputType | true
  _avg?: TechCategoryAvgAggregateInputType
  _sum?: TechCategorySumAggregateInputType
  _min?: TechCategoryMinAggregateInputType
  _max?: TechCategoryMaxAggregateInputType
}

export type TechCategoryGroupByOutputType = {
  id: string
  order: number
  label: string
  createdAt: Date
  updatedAt: Date
  _count: TechCategoryCountAggregateOutputType | null
  _avg: TechCategoryAvgAggregateOutputType | null
  _sum: TechCategorySumAggregateOutputType | null
  _min: TechCategoryMinAggregateOutputType | null
  _max: TechCategoryMaxAggregateOutputType | null
}

export type GetTechCategoryGroupByPayload<T extends TechCategoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TechCategoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TechCategoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TechCategoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TechCategoryGroupByOutputType[P]>
      }
    >
  >



export type TechCategoryWhereInput = {
  AND?: Prisma.TechCategoryWhereInput | Prisma.TechCategoryWhereInput[]
  OR?: Prisma.TechCategoryWhereInput[]
  NOT?: Prisma.TechCategoryWhereInput | Prisma.TechCategoryWhereInput[]
  id?: Prisma.StringFilter<"TechCategory"> | string
  order?: Prisma.IntFilter<"TechCategory"> | number
  label?: Prisma.StringFilter<"TechCategory"> | string
  createdAt?: Prisma.DateTimeFilter<"TechCategory"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechCategory"> | Date | string
  items?: Prisma.TechItemListRelationFilter
}

export type TechCategoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  items?: Prisma.TechItemOrderByRelationAggregateInput
}

export type TechCategoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TechCategoryWhereInput | Prisma.TechCategoryWhereInput[]
  OR?: Prisma.TechCategoryWhereInput[]
  NOT?: Prisma.TechCategoryWhereInput | Prisma.TechCategoryWhereInput[]
  order?: Prisma.IntFilter<"TechCategory"> | number
  label?: Prisma.StringFilter<"TechCategory"> | string
  createdAt?: Prisma.DateTimeFilter<"TechCategory"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TechCategory"> | Date | string
  items?: Prisma.TechItemListRelationFilter
}, "id">

export type TechCategoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TechCategoryCountOrderByAggregateInput
  _avg?: Prisma.TechCategoryAvgOrderByAggregateInput
  _max?: Prisma.TechCategoryMaxOrderByAggregateInput
  _min?: Prisma.TechCategoryMinOrderByAggregateInput
  _sum?: Prisma.TechCategorySumOrderByAggregateInput
}

export type TechCategoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.TechCategoryScalarWhereWithAggregatesInput | Prisma.TechCategoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.TechCategoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TechCategoryScalarWhereWithAggregatesInput | Prisma.TechCategoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TechCategory"> | string
  order?: Prisma.IntWithAggregatesFilter<"TechCategory"> | number
  label?: Prisma.StringWithAggregatesFilter<"TechCategory"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TechCategory"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TechCategory"> | Date | string
}

export type TechCategoryCreateInput = {
  id?: string
  order?: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.TechItemCreateNestedManyWithoutCategoryInput
}

export type TechCategoryUncheckedCreateInput = {
  id?: string
  order?: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.TechItemUncheckedCreateNestedManyWithoutCategoryInput
}

export type TechCategoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.TechItemUpdateManyWithoutCategoryNestedInput
}

export type TechCategoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.TechItemUncheckedUpdateManyWithoutCategoryNestedInput
}

export type TechCategoryCreateManyInput = {
  id?: string
  order?: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechCategoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechCategoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechCategoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechCategoryAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type TechCategoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechCategoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  label?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TechCategorySumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type TechCategoryScalarRelationFilter = {
  is?: Prisma.TechCategoryWhereInput
  isNot?: Prisma.TechCategoryWhereInput
}

export type TechCategoryCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.TechCategoryCreateWithoutItemsInput, Prisma.TechCategoryUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TechCategoryCreateOrConnectWithoutItemsInput
  connect?: Prisma.TechCategoryWhereUniqueInput
}

export type TechCategoryUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.TechCategoryCreateWithoutItemsInput, Prisma.TechCategoryUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.TechCategoryCreateOrConnectWithoutItemsInput
  upsert?: Prisma.TechCategoryUpsertWithoutItemsInput
  connect?: Prisma.TechCategoryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TechCategoryUpdateToOneWithWhereWithoutItemsInput, Prisma.TechCategoryUpdateWithoutItemsInput>, Prisma.TechCategoryUncheckedUpdateWithoutItemsInput>
}

export type TechCategoryCreateWithoutItemsInput = {
  id?: string
  order?: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechCategoryUncheckedCreateWithoutItemsInput = {
  id?: string
  order?: number
  label: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TechCategoryCreateOrConnectWithoutItemsInput = {
  where: Prisma.TechCategoryWhereUniqueInput
  create: Prisma.XOR<Prisma.TechCategoryCreateWithoutItemsInput, Prisma.TechCategoryUncheckedCreateWithoutItemsInput>
}

export type TechCategoryUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.TechCategoryUpdateWithoutItemsInput, Prisma.TechCategoryUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.TechCategoryCreateWithoutItemsInput, Prisma.TechCategoryUncheckedCreateWithoutItemsInput>
  where?: Prisma.TechCategoryWhereInput
}

export type TechCategoryUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.TechCategoryWhereInput
  data: Prisma.XOR<Prisma.TechCategoryUpdateWithoutItemsInput, Prisma.TechCategoryUncheckedUpdateWithoutItemsInput>
}

export type TechCategoryUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TechCategoryUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  label?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TechCategoryCountOutputType
 */

export type TechCategoryCountOutputType = {
  items: number
}

export type TechCategoryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | TechCategoryCountOutputTypeCountItemsArgs
}

/**
 * TechCategoryCountOutputType without action
 */
export type TechCategoryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategoryCountOutputType
   */
  select?: Prisma.TechCategoryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TechCategoryCountOutputType without action
 */
export type TechCategoryCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TechItemWhereInput
}


export type TechCategorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  items?: boolean | Prisma.TechCategory$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.TechCategoryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["techCategory"]>

export type TechCategorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["techCategory"]>

export type TechCategorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["techCategory"]>

export type TechCategorySelectScalar = {
  id?: boolean
  order?: boolean
  label?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TechCategoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "order" | "label" | "createdAt" | "updatedAt", ExtArgs["result"]["techCategory"]>
export type TechCategoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | Prisma.TechCategory$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.TechCategoryCountOutputTypeDefaultArgs<ExtArgs>
}
export type TechCategoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TechCategoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TechCategoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TechCategory"
  objects: {
    items: Prisma.$TechItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    order: number
    label: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["techCategory"]>
  composites: {}
}

export type TechCategoryGetPayload<S extends boolean | null | undefined | TechCategoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload, S>

export type TechCategoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TechCategoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TechCategoryCountAggregateInputType | true
  }

export interface TechCategoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TechCategory'], meta: { name: 'TechCategory' } }
  /**
   * Find zero or one TechCategory that matches the filter.
   * @param {TechCategoryFindUniqueArgs} args - Arguments to find a TechCategory
   * @example
   * // Get one TechCategory
   * const techCategory = await prisma.techCategory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TechCategoryFindUniqueArgs>(args: Prisma.SelectSubset<T, TechCategoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TechCategory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TechCategoryFindUniqueOrThrowArgs} args - Arguments to find a TechCategory
   * @example
   * // Get one TechCategory
   * const techCategory = await prisma.techCategory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TechCategoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TechCategoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechCategory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryFindFirstArgs} args - Arguments to find a TechCategory
   * @example
   * // Get one TechCategory
   * const techCategory = await prisma.techCategory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TechCategoryFindFirstArgs>(args?: Prisma.SelectSubset<T, TechCategoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TechCategory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryFindFirstOrThrowArgs} args - Arguments to find a TechCategory
   * @example
   * // Get one TechCategory
   * const techCategory = await prisma.techCategory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TechCategoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TechCategoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TechCategories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TechCategories
   * const techCategories = await prisma.techCategory.findMany()
   * 
   * // Get first 10 TechCategories
   * const techCategories = await prisma.techCategory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const techCategoryWithIdOnly = await prisma.techCategory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TechCategoryFindManyArgs>(args?: Prisma.SelectSubset<T, TechCategoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TechCategory.
   * @param {TechCategoryCreateArgs} args - Arguments to create a TechCategory.
   * @example
   * // Create one TechCategory
   * const TechCategory = await prisma.techCategory.create({
   *   data: {
   *     // ... data to create a TechCategory
   *   }
   * })
   * 
   */
  create<T extends TechCategoryCreateArgs>(args: Prisma.SelectSubset<T, TechCategoryCreateArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TechCategories.
   * @param {TechCategoryCreateManyArgs} args - Arguments to create many TechCategories.
   * @example
   * // Create many TechCategories
   * const techCategory = await prisma.techCategory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TechCategoryCreateManyArgs>(args?: Prisma.SelectSubset<T, TechCategoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TechCategories and returns the data saved in the database.
   * @param {TechCategoryCreateManyAndReturnArgs} args - Arguments to create many TechCategories.
   * @example
   * // Create many TechCategories
   * const techCategory = await prisma.techCategory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TechCategories and only return the `id`
   * const techCategoryWithIdOnly = await prisma.techCategory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TechCategoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TechCategoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TechCategory.
   * @param {TechCategoryDeleteArgs} args - Arguments to delete one TechCategory.
   * @example
   * // Delete one TechCategory
   * const TechCategory = await prisma.techCategory.delete({
   *   where: {
   *     // ... filter to delete one TechCategory
   *   }
   * })
   * 
   */
  delete<T extends TechCategoryDeleteArgs>(args: Prisma.SelectSubset<T, TechCategoryDeleteArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TechCategory.
   * @param {TechCategoryUpdateArgs} args - Arguments to update one TechCategory.
   * @example
   * // Update one TechCategory
   * const techCategory = await prisma.techCategory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TechCategoryUpdateArgs>(args: Prisma.SelectSubset<T, TechCategoryUpdateArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TechCategories.
   * @param {TechCategoryDeleteManyArgs} args - Arguments to filter TechCategories to delete.
   * @example
   * // Delete a few TechCategories
   * const { count } = await prisma.techCategory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TechCategoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, TechCategoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TechCategories
   * const techCategory = await prisma.techCategory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TechCategoryUpdateManyArgs>(args: Prisma.SelectSubset<T, TechCategoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TechCategories and returns the data updated in the database.
   * @param {TechCategoryUpdateManyAndReturnArgs} args - Arguments to update many TechCategories.
   * @example
   * // Update many TechCategories
   * const techCategory = await prisma.techCategory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TechCategories and only return the `id`
   * const techCategoryWithIdOnly = await prisma.techCategory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TechCategoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TechCategoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TechCategory.
   * @param {TechCategoryUpsertArgs} args - Arguments to update or create a TechCategory.
   * @example
   * // Update or create a TechCategory
   * const techCategory = await prisma.techCategory.upsert({
   *   create: {
   *     // ... data to create a TechCategory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TechCategory we want to update
   *   }
   * })
   */
  upsert<T extends TechCategoryUpsertArgs>(args: Prisma.SelectSubset<T, TechCategoryUpsertArgs<ExtArgs>>): Prisma.Prisma__TechCategoryClient<runtime.Types.Result.GetResult<Prisma.$TechCategoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TechCategories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryCountArgs} args - Arguments to filter TechCategories to count.
   * @example
   * // Count the number of TechCategories
   * const count = await prisma.techCategory.count({
   *   where: {
   *     // ... the filter for the TechCategories we want to count
   *   }
   * })
  **/
  count<T extends TechCategoryCountArgs>(
    args?: Prisma.Subset<T, TechCategoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TechCategoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TechCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TechCategoryAggregateArgs>(args: Prisma.Subset<T, TechCategoryAggregateArgs>): Prisma.PrismaPromise<GetTechCategoryAggregateType<T>>

  /**
   * Group by TechCategory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TechCategoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TechCategoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TechCategoryGroupByArgs['orderBy'] }
      : { orderBy?: TechCategoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TechCategoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTechCategoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TechCategory model
 */
readonly fields: TechCategoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TechCategory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TechCategoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  items<T extends Prisma.TechCategory$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TechCategory$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TechItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TechCategory model
 */
export interface TechCategoryFieldRefs {
  readonly id: Prisma.FieldRef<"TechCategory", 'String'>
  readonly order: Prisma.FieldRef<"TechCategory", 'Int'>
  readonly label: Prisma.FieldRef<"TechCategory", 'String'>
  readonly createdAt: Prisma.FieldRef<"TechCategory", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TechCategory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TechCategory findUnique
 */
export type TechCategoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter, which TechCategory to fetch.
   */
  where: Prisma.TechCategoryWhereUniqueInput
}

/**
 * TechCategory findUniqueOrThrow
 */
export type TechCategoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter, which TechCategory to fetch.
   */
  where: Prisma.TechCategoryWhereUniqueInput
}

/**
 * TechCategory findFirst
 */
export type TechCategoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter, which TechCategory to fetch.
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechCategories to fetch.
   */
  orderBy?: Prisma.TechCategoryOrderByWithRelationInput | Prisma.TechCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechCategories.
   */
  cursor?: Prisma.TechCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechCategories.
   */
  distinct?: Prisma.TechCategoryScalarFieldEnum | Prisma.TechCategoryScalarFieldEnum[]
}

/**
 * TechCategory findFirstOrThrow
 */
export type TechCategoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter, which TechCategory to fetch.
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechCategories to fetch.
   */
  orderBy?: Prisma.TechCategoryOrderByWithRelationInput | Prisma.TechCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TechCategories.
   */
  cursor?: Prisma.TechCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechCategories.
   */
  distinct?: Prisma.TechCategoryScalarFieldEnum | Prisma.TechCategoryScalarFieldEnum[]
}

/**
 * TechCategory findMany
 */
export type TechCategoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter, which TechCategories to fetch.
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TechCategories to fetch.
   */
  orderBy?: Prisma.TechCategoryOrderByWithRelationInput | Prisma.TechCategoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TechCategories.
   */
  cursor?: Prisma.TechCategoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TechCategories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TechCategories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TechCategories.
   */
  distinct?: Prisma.TechCategoryScalarFieldEnum | Prisma.TechCategoryScalarFieldEnum[]
}

/**
 * TechCategory create
 */
export type TechCategoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * The data needed to create a TechCategory.
   */
  data: Prisma.XOR<Prisma.TechCategoryCreateInput, Prisma.TechCategoryUncheckedCreateInput>
}

/**
 * TechCategory createMany
 */
export type TechCategoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TechCategories.
   */
  data: Prisma.TechCategoryCreateManyInput | Prisma.TechCategoryCreateManyInput[]
}

/**
 * TechCategory createManyAndReturn
 */
export type TechCategoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * The data used to create many TechCategories.
   */
  data: Prisma.TechCategoryCreateManyInput | Prisma.TechCategoryCreateManyInput[]
}

/**
 * TechCategory update
 */
export type TechCategoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * The data needed to update a TechCategory.
   */
  data: Prisma.XOR<Prisma.TechCategoryUpdateInput, Prisma.TechCategoryUncheckedUpdateInput>
  /**
   * Choose, which TechCategory to update.
   */
  where: Prisma.TechCategoryWhereUniqueInput
}

/**
 * TechCategory updateMany
 */
export type TechCategoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TechCategories.
   */
  data: Prisma.XOR<Prisma.TechCategoryUpdateManyMutationInput, Prisma.TechCategoryUncheckedUpdateManyInput>
  /**
   * Filter which TechCategories to update
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * Limit how many TechCategories to update.
   */
  limit?: number
}

/**
 * TechCategory updateManyAndReturn
 */
export type TechCategoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * The data used to update TechCategories.
   */
  data: Prisma.XOR<Prisma.TechCategoryUpdateManyMutationInput, Prisma.TechCategoryUncheckedUpdateManyInput>
  /**
   * Filter which TechCategories to update
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * Limit how many TechCategories to update.
   */
  limit?: number
}

/**
 * TechCategory upsert
 */
export type TechCategoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * The filter to search for the TechCategory to update in case it exists.
   */
  where: Prisma.TechCategoryWhereUniqueInput
  /**
   * In case the TechCategory found by the `where` argument doesn't exist, create a new TechCategory with this data.
   */
  create: Prisma.XOR<Prisma.TechCategoryCreateInput, Prisma.TechCategoryUncheckedCreateInput>
  /**
   * In case the TechCategory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TechCategoryUpdateInput, Prisma.TechCategoryUncheckedUpdateInput>
}

/**
 * TechCategory delete
 */
export type TechCategoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
  /**
   * Filter which TechCategory to delete.
   */
  where: Prisma.TechCategoryWhereUniqueInput
}

/**
 * TechCategory deleteMany
 */
export type TechCategoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TechCategories to delete
   */
  where?: Prisma.TechCategoryWhereInput
  /**
   * Limit how many TechCategories to delete.
   */
  limit?: number
}

/**
 * TechCategory.items
 */
export type TechCategory$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechItem
   */
  select?: Prisma.TechItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechItem
   */
  omit?: Prisma.TechItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechItemInclude<ExtArgs> | null
  where?: Prisma.TechItemWhereInput
  orderBy?: Prisma.TechItemOrderByWithRelationInput | Prisma.TechItemOrderByWithRelationInput[]
  cursor?: Prisma.TechItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TechItemScalarFieldEnum | Prisma.TechItemScalarFieldEnum[]
}

/**
 * TechCategory without action
 */
export type TechCategoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TechCategory
   */
  select?: Prisma.TechCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the TechCategory
   */
  omit?: Prisma.TechCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TechCategoryInclude<ExtArgs> | null
}
